<ul class="nav nav-tabs" id="myTab" role="tablist">
	<li class="nav-item">
		<a class="nav-link" href="#" role="tab" id="tweets"><?= $this->view->total_tweets['total_tweets']?> Tweets</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="#" id="seguindo"><?= $this->view->total_seguindo['total_seguindo'] ?> Seguindo</a>
	</li>
	<li class="nav-item">
		<a class="nav-link active bg-primary text-white" href="#" id="seguidores"><?= $this->view->total_seguidores['total_seguidores'] ?> Seguidores</a>
	</li>
</ul>

<?php foreach ($this->view->usuarios as $indice_arr => $usuario) { if($usuario['seguidor_sn'] == 0){continue;}?>
	<div class="card">
		<div class="card-body d-flex">
			<div>
		    	<img src="<?= !empty($usuario['path']) ? $usuario['path']: 'fotos_usuarios/sem_foto.png'?>" class="rounded-circle me-2" width="45px" height="45px" id="<?= $usuario['id'] == $_SESSION['id'] ? '' : 'usuario';?>" value="<?= $usuario['id']?>">
		    </div>
			<div>
				<p id="<?= $usuario['id'] == $_SESSION['id'] ? '' : 'usuario';?>" value="<?= $usuario['id']?>"><?= $usuario['nome']?></p>
				<?php if($usuario['seguindo_sn'] == 0) {?>
				<a href="acao?acao=seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-outline-primary rounded-pill" id="seguir" value="<?=$usuario['id']?>">Seguir</a>
				<?php }?>
				
				<?php if($usuario['seguindo_sn'] == 1) {?>
				<a href="acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-primary rounded-pill" id="deixar_de_seguir" value="<?=$usuario['id']?>">Seguindo</a>
				<?php }?>
			</div>
		</div>
	</div>
<?php } if($this->view->total_seguidores['total_seguidores'] == 0){?>

	<div class="card card-nullmessage">
		<div class="card-body text-center">
			<img class="img-fluid" src="img/nullmessage1.png">
			<h4 class="card-title mt-2 text-muted">Você ainda não tem seguidores</h5>
			<h6 class="card-subtitle mb-2 text-muted">Poste coisas interessantes para aumentar sua popularidade</h6>
		</div>
	</div>

<?php } ?>