<?php foreach ($this->view->usuarios as $indice_arr => $usuario) {?>
	<div class="card">
		<div class="card-body d-flex">
			<div>
		    	<img src="<?= !empty($usuario['path']) ? $usuario['path']: 'fotos_usuarios/sem_foto.png'?>" class="rounded-circle me-2" width="45px" height="45px">
		    </div>
			<div>
				<p><?= $usuario['nome']?></p>
			    <?php if($usuario['seguindo_sn'] == 0) {?>
				<a href="acao?acao=seguir&id_usuario=<?=$usuario['id']?>&pesquisarPor=<?=$this->view->nome_usuario?>" class="btn btn-success" id="seguir" value="<?=$usuario['id']?>">Seguir</a>
				<?php }?>
				
				<?php if($usuario['seguindo_sn'] == 1) {?>
				<a href="acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>&pesquisarPor=<?=$this->view->nome_usuario?>" class="btn btn-danger" id="deixar_de_seguir" value="<?=$usuario['id']?>">Deixar de seguir</a>
				<?php }?>
			</div>
		</div>
	</div>
<?php } if(empty($this->view->usuarios)){?>

	<div class="card card-nullmessage">
		<div class="card-body text-center">
			<img class="img-fluid" src="img/nullmessage2.png">
			<h4 class="card-title ">Não encontramos ninguém </h5>
			<h6 class="card-subtitle mb-2 ">Tente pesquisar com outro nome</h6>
		</div>
	</div>

<?php } ?>