<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
			<img src="img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>
<?php //echo"<pre>"; print_r($this->view->seguindo_sn); echo('</pre>'); ?>

<div class="mt-5">

	<?php if(isset($this->view->nome_usuario)){?>
	
	<div class="perfil-info">
		
		<div class="perfil-capa" style=""></div>

		<div class="perfil-foto"><img src="<?= !empty($this->view->foto) ? $this->view->foto : 'fotos_usuarios/sem_foto.png'?>"></div>

		<div class="perfil-data">
			
			<div class="dados-perfil">
				<p class="nomeUsuario">
					<?= $this->view->nome_usuario?>
				</p>
			</div>
			
		</div>

		<!-- Button trigger modal Mudar Foto -->
		<div class="editar-perfil">
		    <?php if($this->view->seguindo_sn == 0) {?>
				<a href="acao?acao=seguir&id_usuario=<?=$_GET['usuario']?>" class="btn btn-outline-primary rounded-pill" id="seguir" value="<?=$_GET['usuario']?>">Seguir</a>
			<?php }?>
			
			<?php if($this->view->seguindo_sn != 0) {?>
				<a href="acao?acao=deixar_de_seguir&id_usuario=<?=$_GET['usuario']?>" class="btn btn-primary rounded-pill" id="deixar_de_seguir" value="<?=$_GET['usuario']?>">Seguindo</a>
			<?php }?>
		</div>


		<?php include('_includes/modals.phtml'); ?>

		<div class="perfil-tweets" style="">

			<!-- Carregar informações da página (tweets, seguindo e seguidores) -->
			<div id="content">
				
			</div>

		</div>

	</div>

	<?php }else{?>
		<div class="card card-nullmessage border-0">
			<div class="card-body text-center">
				<img class="img-fluid" src="img/nullmessage4.png">
				<h4 class="card-title text-muted">Este usuário não existe mais</h5>
				<h6 class="card-subtitle mb-2 text-muted">Procuramos em todos os cantos do mundo, mas não há ninguém</h6>
				<button class="btn btn-primary mt-2" id="voltarPagina">Voltar a navegar</button>
			</div>
		</div>
	<?php }?>

	<div class="footer" id="footer">
		<div class="icons">
			<div class="row justify-content-center">
				<div class="col-2 col-md-1">
					<a href="timeline" id="timeline"><i class="fas fa-home"></i></a>
				</div>
				<div class="col-2 col-md-1">
					<a href="perfil"><i class="fas fa-user"><span class="disabled-circle-profile"></span></i></a>
				</div>
				<div class="col-2 col-md-1">
					<a href="quem_seguir" id="quem_seguir"><i class="fas fa-search"></i></a>
				</div>
				<div class="col-2 col-md-1">
					<a href="#footer"><i class="fas fa-sign-out-alt"></i></a>
				</div>
			</div>
		</div>
	</div>

</div>

<script>
$(document).ready(function() {

	var tweets;
	var seguindo;
	var curtidas;
	var comentarios;

	// Obtém a string da URL
    var urlParams = new URLSearchParams(window.location.search);

    // Obtém o valor do parâmetro 'usuario'
    var usuario = urlParams.get('usuario');

	//carregar tweets
	$.ajax({
        type: 'GET',
        url: 'usuarioTweets?usuario=' + usuario,
        success: function(data) {
            $("#content").html(data);
        },
        error: function() {
            alert("Erro ao carregar a view seguindo.");
        }
    });

    // FUNÇÕES *************************************************************************************************************
    function carregarTweetsUsuario(){
		$.ajax({
            type: 'GET',
            url: 'usuarioTweets?usuario=' + usuario,
            success: function(data) {
                $("#content").html(data);
            },
            error: function() {
                alert("Erro ao carregar a view seguindo.");
            }
        });
	}

    //função para recuperar comentários
	function recuperarComentários(id_tweet){
		$.ajax({
	        type: 'GET',
	        url: 'recuperar_comentario?id_tweet=' + id_tweet,
	        success: function(data) {
	            $("#content-comment-" + id_tweet).html(data);
	        },
	        error: function() {
	            alert("Erro ao carregar a view tweets.");
	        }
	    });
	}

	function carregarSeguindoUsuario(){
		$.ajax({
            type: 'GET',
            url: 'usuarioSeguindo?usuario=' + usuario,
            success: function(data) {
                $("#content").html(data);
            },
            error: function() {
                alert("Erro ao carregar a view seguindo.");
            }
        });
	}

	function carregarSeguidoresUsuario(){
		$.ajax({
            type: 'GET',
            url: 'usuarioSeguidores?usuario=' + usuario,
            success: function(data) {
                $("#content").html(data);
            },
            error: function() {
                alert("Erro ao carregar a view de seguidores.");
            }
        });
	}

    // Carregar views *************************************************************************************************************
	//recuperar tweets
    $("#content").on("click", "#tweets", function(){
        carregarTweetsUsuario();
    });

    $("#content").on("click", "#seguindo", function(){
        carregarSeguindoUsuario();
    });

    $("#content").on("click", "#seguidores", function(){
        carregarSeguidoresUsuario();
    });

    // FUNCIONALIDADES *************************************************************************************************************

    //carregar perfil usuario
	$("body").on("click", "#usuario", function(){
		window.location.assign("usuarioPerfil?usuario=" + $(this).attr('value'));
	});

    // Utiliza o histórico do navegador para voltar uma página
	$("body").on("click", "#voltarPagina", function(){
      window.history.back();
    })

    //deixar de seguir
    $("body").on("click", "a#deixar_de_seguir", function(e){
		e.preventDefault();

        //alert($(this).attr('value'));
        $.ajax({
            url: $(this).attr('href'),
            type: 'get',
            success: function(data) {
            },
            error: function() {
                alert("Erro ao carregar a view de seguindo.");
            }
    	});

    	//alterar botao deixar_de_seguir para seguir 
        $(this).attr('href', 'acao?acao=seguir&id_usuario='+$(this).attr('value') +'&pagina=recuperarSeguindo');
        $(this).attr('class', 'btn btn-outline-primary rounded-pill');
        $(this).attr('id', 'seguir');
        $(this).html('Seguir');
	});

    //seguir
    $("body").on("click", "a#seguir", function(e){
		e.preventDefault();

        //alert($(this).attr('value'));
        $.ajax({
            url: $(this).attr('href'),
            type: 'get',
            success: function(data) {
            },
            error: function() {
                alert("Erro ao carregar a view de seguindo.");
            }
    	});

    	//alterar botao seguir para deixar_de_seguir 
        $(this).attr('href', 'acao?acao=deixar_de_seguir&id_usuario='+$(this).attr('value') +'&pagina=recuperarSeguindo');
        $(this).attr('class', 'btn btn-primary rounded-pill');
        $(this).attr('id', 'deixar_de_seguir');
        $(this).html('Seguindo');
	});

	//curtir tweet
    $("body").on("click", "#curtir", function(e){
		e.preventDefault();

		//recuperar número de curtidas
		curtidas = $("#curtidasTweet" + $(this).attr('value')).html();
		curtidas = parseInt(curtidas);

		$.ajax({
            type: 'get',
            url: $(this).attr('href'),
            success: function(data) {
        		//carregarTweetsTimeline();
            },
            error: function() {
                alert("Erro ao carregar a view pesquisar.");
            }
        });

        //alterar número de curtidas
    	$("#curtidasTweet" + $(this).attr('value')).html((curtidas + 1));

    	//alterar botao curtir para descurtir 
        $(this).attr('href', 'acao?acao=descurtirTweet&id_tweet='+$(this).attr('value'));
        $(this).find('i').attr('class', 'fas fa-heart text-danger');
        $(this).attr('id', 'descurtir');

    });

    //descurtir tweet
    $("body").on("click", "#descurtir", function(e){
		e.preventDefault();

		//recuperar número de curtidas
		curtidas = $("#curtidasTweet" + $(this).attr('value')).html();
		curtidas = parseInt(curtidas);

		$.ajax({
            type: 'get',
            url: $(this).attr('href'),
            success: function(data) {
        		//carregarTweetsTimeline();
            },
            error: function() {
                alert("Erro ao carregar a view pesquisar.");
            }
        });

        //alterar número de curtidas
    	($("#curtidasTweet" + $(this).attr('value')).html((curtidas - 1)));

    	//alterar botao curtir para descurtir 
        $(this).attr('href', 'acao?acao=curtirTweet&id_tweet='+$(this).attr('value'));
        $(this).find('i').attr('class', 'far fa-heart');
        $(this).attr('id', 'curtir');

    });

    //exibir-ou-deixar de exibir comentário 
	$("body").on("click", "#exibirCometariosTweet", function(e){
		e.preventDefault();

		var id_tweet = $(this).attr('value');

		//recuperar comentários
		recuperarComentários(id_tweet);

		$("#comentariosTweet" + id_tweet).toggleClass('d-none');

    });

    //adicionar comentário
	$("body").on("submit", "#comentarioForm form", function(e){
		e.preventDefault();

		id_tweet = $(this).find('input[name="id_tweet"]').attr("value");

		//recuperar número de comentários
		comentarios = $("#countComentariosTweet" + id_tweet).html();
		comentarios = parseInt(comentarios);

		
		//desativar botão de comentar
		$(this).find('button').addClass("disabled");

		$.ajax({
	        type: 'POST',
	        url: 'comentario',
	        data: $(this).serialize(),
	        dataType: 'json',
	        success: function(data) {
	            recuperarComentários(id_tweet);
	        },
	        error: function() {
	            alert("Erro ao carregar a view tweets.");
	        }
	    }).done(function(){
	    	//limpar input de comentário
	    	$('#adicionarComentario' + id_tweet).val("");
	    	//ativar botão de comentar
	    	$('#enviarComentario' + id_tweet).removeClass("disabled");
	    });

        //alterar número de comentários
    	$("#countComentariosTweet" + id_tweet).html(comentarios + 1);
		
    });

	//excluir comentário
	$("body").on("click", "#removerComentario", function(e){
		e.preventDefault();

		id_tweet = $(this).attr("name");

		//recuperar número de comentários
		comentarios = $("#countComentariosTweet" + id_tweet).html();
		comentarios = parseInt(comentarios);

		$.ajax({
	        type: 'GET',
	        url: $(this).attr('href'),
	        success: function(data) {
	        },
	        error: function() {
	            alert("Erro ao carregar a view tweets.");
	        }
	    });

	    //alterar número de comentários
    	$("#countComentariosTweet" + id_tweet).html(comentarios - 1);

    	//remover display do comentário excluido
	    $("#container-comentario" + $(this).attr("value")).addClass("d-none");
		
    });

	//curtir comentário
	$("#content").on("click", "#curtirComentario", function(e){
		e.preventDefault();

		id_tweet = $(this).attr("value");

		//recuperar número de curtidas
		curtidas = $("#curtidasComentario" + id_tweet).html();
		curtidas = parseInt(curtidas);

		$.ajax({
            type: 'get',
            url: $(this).attr('href'),
            success: function(data) {
            },
            error: function() {
                alert("Erro ao carregar a view.");
            }
        });

        //alterar número de curtidas
    	$("#curtidasComentario" + id_tweet).html((curtidas + 1));

    	//alterar botao curtir para descurtir 
        $(this).attr('href', 'acao?acao=descurtirComentario&id_comentario='+id_tweet);
        $(this).find('i').attr('class', 'fas fa-heart text-danger');
        $(this).attr('id', 'descurtirComentario');
		
    });


    //descurtir comentario
    $("#content").on("click", "#descurtirComentario", function(e){
		e.preventDefault();

		id_tweet = $(this).attr("value");

		//recuperar número de curtidas
		curtidas = $("#curtidasComentario" + id_tweet).html();
		curtidas = parseInt(curtidas);

		$.ajax({
            type: 'get',
            url: $(this).attr('href'),
            success: function(data) {
            },
            error: function() {
                alert("Erro ao carregar a view pesquisar.");
            }
        });

        //alterar número de curtidas
    	($("#curtidasComentario" + id_tweet).html((curtidas - 1)));

    	//alterar botao curtir para descurtir
        $(this).attr('href', 'acao?acao=curtirComentario&id_comentario='+id_tweet);
        $(this).find('i').attr('class', 'far fa-heart');
        $(this).attr('id', 'curtirComentario');

    });

});
</script>