<ul class="nav nav-tabs" id="myTab" role="tablist">
	<li class="nav-item">
		<a class="nav-link active bg-primary text-white" href="#" role="tab" id="tweets"><?= $this->view->total_tweets['total_tweets']?> Tweets</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="#" id="seguindo"><?= $this->view->total_seguindo['total_seguindo'] ?> Seguindo</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="#" id="seguidores"><?= $this->view->total_seguidores['total_seguidores'] ?> Seguidores</a>
	</li>
</ul>

<?php //echo"<pre>"; print_r($this->view->tweets); echo('</pre>'); ?>

<?php foreach($this->view->tweets as $id_tweet => $tweet) {?>
	<div class="card" id="card-tweet-<?= $tweet['id']?>">
		<div class="card-body d-flex">
			<div>
		    	<img src="<?= !empty($tweet['path']) ? $tweet['path']: 'fotos_usuarios/sem_foto.png'?>" class="rounded-circle me-2" width="45px" height="45px">
		    </div>
			<div>
				<p><strong><?= $tweet['nome']?></strong> <small><span class="text text-muted">- <?= $tweet['data']?></span></small><?php if($tweet['id_usuario'] == $_SESSION['id']){?><a href="remover_tweet?id_tweet=<?= $tweet['id']?>" class="botao-tweet" id="removerTweet" value="<?=$tweet['id']?>" ><i class="far fa-trash-alt" class="text-danger"></i></a><?php }?></p>
		        <p class="card-text text-break"><?= $tweet['tweet']?></p>
		        <p class="card-text">
		        	<small class="text-muted">
		        		<span class="me-3">
		        			<?php if($tweet['curtido_sn'] == 0){?>
			        			<a href="acao?acao=curtirTweet&id_tweet=<?=$tweet['id']?>" class="text-secondary text-decoration-none" id="curtir" value="<?=$tweet['id']?>">
				        			<i class="far fa-heart"></i>
			        			</a>
		        			<?php } if($tweet['curtido_sn'] == 1){?>
			        			<a href="acao?acao=descurtirTweet&id_tweet=<?=$tweet['id']?>" class="text-secondary text-decoration-none" id="descurtir" value="<?=$tweet['id']?>">
				        			<i class="fas fa-heart text-danger"></i>
			        			</a>
		        			<?php } ?>
		        			<span id="curtidasTweet<?=$tweet['id']?>">
			        			<?=$tweet['curtidas']?>
		        			</span>
		        		</span>
		        		<span>
		        			<a href="recuperar_comentario?id_tweet=<?=$tweet['id']?>" class="text-secondary text-decoration-none" id="exibirCometariosTweet" value="<?= $tweet['id']?>">
			        			<i class="far fa-comment"></i>
		        			</a>

			        		<span id="countComentariosTweet<?=$tweet['id']?>">
			        			<?=$tweet['count_comentarios']?>
		        			</span>
		        		</span>
  					</small>
		        </p>
			</div>
		</div>

		<!-- Comentários -->
		<div class="ms-4 position-relative d-none" id="comentariosTweet<?= $tweet['id']?>">

			<div id="comentarioForm">
				<form>
					<div class="input-group mb-3 px-3">
						<input type="text" class="form-control" placeholder="Adicionar comentário" name="comentario" id="adicionarComentario<?= $tweet['id']?>" required style="max-width: 400px;" maxlength="140">
						<input type="hidden" value="<?= $tweet['id']?>" name="id_tweet">
						<button type="submit" class="btn btn-outline-primary" id="enviarComentario<?= $tweet['id']?>">enviar</button>
					</div>
				</form>
			</div>
				
			<div id="content-comment-<?= $tweet['id']?>"></div>
			
		</div>
	</div>
<?php } if($this->view->total_tweets['total_tweets'] == 0){?>

	<div class="card card-nullmessage">
		<div class="card-body text-center">
			<img class="img-fluid" src="img/nullmessage.png">
			<h4 class="card-title text-muted"><?= $this->view->nome_usuario?> ainda não postou nada</h5>
		</div>
	</div>

<?php } ?>