<span id="content">
	<style type="text/css">
	html,body{
  		padding-bottom: 0px;
	}
	</style>

	<div class="container-fluid h-100">
		<div class="row h-100">
	    
	    <div class="col-lg-6 banner">
	    	<div class="row h-100 justify-content-center align-items-center">
	    		<div>
					<div class="communicationItem">
						<i class="fas fa-search fa-2x mr-3"></i>
						Siga o que lhe interessa.
					</div>
					<div class="communicationItem">
						<i class="fas fa-user-friends fa-2x mr-3"></i>
						Saiba sobre o que as pessoas estão falando.
					</div>
					<div class="communicationItem">
						<i class="far fa-comment fa-2x mr-3"></i>
						Participe da conversa.
					</div>
				</div>
			</div>
	    </div>

	    <div class="col-lg-6 pt-4 pl-5 pr-5" id="autenticar">
			<form action="autenticar" method="post">
				<div class="row">
					<div class="col-xl">
						<input type="text" name="email" class="form-control" placeholder="E-mail" style="max-width: 400px;">
					</div>
					<div class="col-xl">
						<input type="password" name="senha" class="form-control" placeholder="Senha" style="max-width: 400px;">
					</div>
					<div class="col-xl">
						<button type="submit" class="btn btn-primary mb-2">Entrar</button>
					</div>
				</div>

				<div class="row">
					<?php if(isset($this->view->cadastro)){?>
					<div class="col">
						<p class="text text-success">Cadastro realizado com sucesso!</p>
					</div>
					<?php }?>
					<div class="col">
						<span class="text text-danger" id="mensagem"></span>
					</div>
				</div>
			</form>

			<div class="texto">
				<div class="">
					<img width="51px" height="40" src="img/twitter_logo.png" />
					<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

					<h2 class="subtitle">Participe hoje do Twitter.</h2>
					<a href="inscreverse" class="btn btn-primary btn-block mb-2" id="inscreverse" style="max-width: 200px;">Inscrever-se</a>
				</div>	
			</div>


	    </div>

	  </div>
	</div>
</span>

<script>
$(document).ready(function(){

	// FUNÇÕES ***************************************************************************************************************
    function carregarIndex(href){
    	$.ajax({
            type: 'GET',
            url: href,
            success: function(data) {
        		$("#content").html(data);
            },
            error: function() {
                alert("Erro ao carregar a view index.");
            }
        });
    };
	
	function carregarInscreverse(href){
	    	$.ajax({
	            type: 'GET',
	            url: href,
	            success: function(data) {
	        		$("#content").html(data);
	            },
	            error: function() {
	                alert("Erro ao carregar a view inscreverse.");
	            }
	        });
	    };

    // Carregar views *************************************************************************************************************

    //recuperar inscreverse
	$("body").on("click", "#inscreverse", function(e){
        e.preventDefault();
        carregarInscreverse($(this).attr('href'));
    });


    // FUNCIONALIDADES *************************************************************************************************************
    //autenticar
	$("body").on("submit", "#autenticar form", function(e){
        e.preventDefault();

        //enviar dados
        $.ajax({
            type: 'POST',
            url: 'autenticar',
            data: $(this).serialize(),
            dataType: 'json',
            success: function(data) {
        		if(data.success){
        			window.location.href = data.redirect;
        		}else{
        			$("#mensagem").html(data.message);
        		}
        		
            },
            error: function() {
                alert("Erro ao carregar a view autenticar.");
            }
        });
    });

    //registrar
	$("body").on("submit", "#registrar form", function(e){
        e.preventDefault();

        //enviar dados
        $.ajax({
            type: 'POST',
            url: 'registrar',
            data: $(this).serialize(),
            dataType: 'json',
            success: function(data) {
        		if(data.success){
        			window.location.href = data.redirect;
        		}else{
        			$("#mensagemErro").html(data.message);
        		}
        		
            },
            error: function() {
                alert("Erro ao carregar a view autenticar.");
            }
        });
    });

})
</script>