<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="img/twitter_logo.png" width="40px" height="40px">
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col" id="registrar">
            
            <form action="registrar" method="post">
              <div class="mb-3">
                <input type="text" value="" name="nome" class="form-control" placeholder="Nome" maxlength="13" minlength="3">
                <span class="text text-danger" id="erroNome"></span>
              </div>
              
              <div class="mb-3">
                <input type="email" value="" name="email" class="form-control" placeholder="E-mail">
                <span class="text text-danger" id="erroEmail"></span>
              </div>

              <div class="mb-3">
                <input type="password" value="" name="senha" class="form-control" placeholder="Senha" maxlength="32" minlength="3">
              </div>

              <div class="row">
                <div class="col">
                  <span class="text text-danger" id="mensagemErro"></span>
                </div>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  